# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evolver Labs
email: dane@evolverlabs.com
description: >
  Evolver Labs creates online products and provides web hosting and development. Specializing in services for writers and artists.
url: "http://www.evolverlabs.com"
twitter_username: evolverlabs
github_username:  daneclarkcollins

# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Dane Collins
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
